// <auto-generated />
namespace Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTopic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTopic));
        
        string IMigrationMetadata.Id
        {
            get { return "201304071946280_Add Topic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
