// <auto-generated />
namespace Models.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddRecord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRecord));
        
        string IMigrationMetadata.Id
        {
            get { return "201304251500278_Add Record"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
