// <auto-generated />
namespace Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddImagetoSection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddImagetoSection));
        
        string IMigrationMetadata.Id
        {
            get { return "201303310807266_Add Image to Section"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
