// <auto-generated />
namespace Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ResizeUserEmailLengthRestriction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResizeUserEmailLengthRestriction));
        
        string IMigrationMetadata.Id
        {
            get { return "201305071630438_Resize User Email Length Restriction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
